schema: 3
written_by: 0.15.1
skills_version: 0.15.1
name: xclconfig
command: spektacular
agent: claude
spec_trigger_threshold: moderate
debug:
    enabled: false
spec:
    provider: file
    id_method: timestamp
    config:
        directory: specs
plan:
    provider: file
    config:
        directory: plans
changelog:
    provider: file
    config:
        directory: changelog
design:
    sources:
        - name: design
          provider: file
          config:
            location: design
repos:
    - name: xclconfig
      location: .
    - name: xcl-website
      location: ../../xcl-website/.spektacular
