schema: 4
written_by: dev
skills_version: dev
name: xclconfig
command: spektacular
agent: claude
spec_trigger_threshold: moderate
epic_split_threshold: moderate
auto_commit: "off"
debug:
    enabled: false
spec:
    provider: file
    id_method: timestamp
    config:
        directory: specs
plan:
    provider: file
    strict_spec_changes: false
    config:
        directory: plans
    task_id:
        provider: uuid
changelog:
    provider: file
    config:
        directory: changelog
epic:
    provider: file
    strict_dependencies: false
    config:
        directory: epics
implement:
    worktrees: true
design:
    sources:
        - name: design
          provider: file
          config:
            location: design
repos:
    - name: xcl
      location: .
    - name: xcl-website
      location: ../../xcl-website/.spektacular
    - name: xcl-vscode
      location: ../../xcl-vscode/.spektacular
    - name: xcl-plugin-template
      location: /home/nicj/code/github.com/jumppad-labs/xcl-plugin-template/.spektacular
    - name: xcl-plugin-docker
      location: ../../xcl-plugin-docker/.spektacular
