// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jumppad-labs/xcl/example/plugin/plugins/docker/client/containers"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTasks creates a new instance of MockTasks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTasks(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTasks {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTasks{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTasks is an autogenerated mock type for the Tasks type
type MockTasks struct {
	mock.Mock
}

type MockTasks_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTasks) EXPECT() *MockTasks_Expecter {
	return &MockTasks_Expecter{mock: &_m.Mock}
}

// ConnectNetwork provides a mock function for the type MockTasks
func (_mock *MockTasks) ConnectNetwork(ctx context.Context, network string, containerID string, aliases []string) error {
	ret := _mock.Called(ctx, network, containerID, aliases)

	if len(ret) == 0 {
		panic("no return value specified for ConnectNetwork")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) error); ok {
		r0 = returnFunc(ctx, network, containerID, aliases)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTasks_ConnectNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectNetwork'
type MockTasks_ConnectNetwork_Call struct {
	*mock.Call
}

// ConnectNetwork is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - containerID string
//   - aliases []string
func (_e *MockTasks_Expecter) ConnectNetwork(ctx any, network any, containerID any, aliases any) *MockTasks_ConnectNetwork_Call {
	return &MockTasks_ConnectNetwork_Call{Call: _e.mock.On("ConnectNetwork", ctx, network, containerID, aliases)}
}

func (_c *MockTasks_ConnectNetwork_Call) Run(run func(ctx context.Context, network string, containerID string, aliases []string)) *MockTasks_ConnectNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTasks_ConnectNetwork_Call) Return(err error) *MockTasks_ConnectNetwork_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTasks_ConnectNetwork_Call) RunAndReturn(run func(ctx context.Context, network string, containerID string, aliases []string) error) *MockTasks_ConnectNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerAddresses provides a mock function for the type MockTasks
func (_mock *MockTasks) ContainerAddresses(ctx context.Context, containerID string) (map[string]string, error) {
	ret := _mock.Called(ctx, containerID)

	if len(ret) == 0 {
		panic("no return value specified for ContainerAddresses")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return returnFunc(ctx, containerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = returnFunc(ctx, containerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, containerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTasks_ContainerAddresses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerAddresses'
type MockTasks_ContainerAddresses_Call struct {
	*mock.Call
}

// ContainerAddresses is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
func (_e *MockTasks_Expecter) ContainerAddresses(ctx any, containerID any) *MockTasks_ContainerAddresses_Call {
	return &MockTasks_ContainerAddresses_Call{Call: _e.mock.On("ContainerAddresses", ctx, containerID)}
}

func (_c *MockTasks_ContainerAddresses_Call) Run(run func(ctx context.Context, containerID string)) *MockTasks_ContainerAddresses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTasks_ContainerAddresses_Call) Return(stringToString map[string]string, err error) *MockTasks_ContainerAddresses_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockTasks_ContainerAddresses_Call) RunAndReturn(run func(ctx context.Context, containerID string) (map[string]string, error)) *MockTasks_ContainerAddresses_Call {
	_c.Call.Return(run)
	return _c
}

// CreateContainer provides a mock function for the type MockTasks
func (_mock *MockTasks) CreateContainer(ctx context.Context, spec containers.ContainerSpec) (string, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for CreateContainer")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, containers.ContainerSpec) (string, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, containers.ContainerSpec) string); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, containers.ContainerSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTasks_CreateContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateContainer'
type MockTasks_CreateContainer_Call struct {
	*mock.Call
}

// CreateContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - spec containers.ContainerSpec
func (_e *MockTasks_Expecter) CreateContainer(ctx any, spec any) *MockTasks_CreateContainer_Call {
	return &MockTasks_CreateContainer_Call{Call: _e.mock.On("CreateContainer", ctx, spec)}
}

func (_c *MockTasks_CreateContainer_Call) Run(run func(ctx context.Context, spec containers.ContainerSpec)) *MockTasks_CreateContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 containers.ContainerSpec
		if args[1] != nil {
			arg1 = args[1].(containers.ContainerSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTasks_CreateContainer_Call) Return(s string, err error) *MockTasks_CreateContainer_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTasks_CreateContainer_Call) RunAndReturn(run func(ctx context.Context, spec containers.ContainerSpec) (string, error)) *MockTasks_CreateContainer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNetwork provides a mock function for the type MockTasks
func (_mock *MockTasks) CreateNetwork(ctx context.Context, name string, spec containers.NetworkSpec) (string, error) {
	ret := _mock.Called(ctx, name, spec)

	if len(ret) == 0 {
		panic("no return value specified for CreateNetwork")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, containers.NetworkSpec) (string, error)); ok {
		return returnFunc(ctx, name, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, containers.NetworkSpec) string); ok {
		r0 = returnFunc(ctx, name, spec)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, containers.NetworkSpec) error); ok {
		r1 = returnFunc(ctx, name, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTasks_CreateNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNetwork'
type MockTasks_CreateNetwork_Call struct {
	*mock.Call
}

// CreateNetwork is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - spec containers.NetworkSpec
func (_e *MockTasks_Expecter) CreateNetwork(ctx any, name any, spec any) *MockTasks_CreateNetwork_Call {
	return &MockTasks_CreateNetwork_Call{Call: _e.mock.On("CreateNetwork", ctx, name, spec)}
}

func (_c *MockTasks_CreateNetwork_Call) Run(run func(ctx context.Context, name string, spec containers.NetworkSpec)) *MockTasks_CreateNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 containers.NetworkSpec
		if args[2] != nil {
			arg2 = args[2].(containers.NetworkSpec)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTasks_CreateNetwork_Call) Return(s string, err error) *MockTasks_CreateNetwork_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTasks_CreateNetwork_Call) RunAndReturn(run func(ctx context.Context, name string, spec containers.NetworkSpec) (string, error)) *MockTasks_CreateNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// DisconnectNetwork provides a mock function for the type MockTasks
func (_mock *MockTasks) DisconnectNetwork(ctx context.Context, network string, containerID string) error {
	ret := _mock.Called(ctx, network, containerID)

	if len(ret) == 0 {
		panic("no return value specified for DisconnectNetwork")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, network, containerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTasks_DisconnectNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisconnectNetwork'
type MockTasks_DisconnectNetwork_Call struct {
	*mock.Call
}

// DisconnectNetwork is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - containerID string
func (_e *MockTasks_Expecter) DisconnectNetwork(ctx any, network any, containerID any) *MockTasks_DisconnectNetwork_Call {
	return &MockTasks_DisconnectNetwork_Call{Call: _e.mock.On("DisconnectNetwork", ctx, network, containerID)}
}

func (_c *MockTasks_DisconnectNetwork_Call) Run(run func(ctx context.Context, network string, containerID string)) *MockTasks_DisconnectNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTasks_DisconnectNetwork_Call) Return(err error) *MockTasks_DisconnectNetwork_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTasks_DisconnectNetwork_Call) RunAndReturn(run func(ctx context.Context, network string, containerID string) error) *MockTasks_DisconnectNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureImage provides a mock function for the type MockTasks
func (_mock *MockTasks) EnsureImage(ctx context.Context, ref string) error {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for EnsureImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTasks_EnsureImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureImage'
type MockTasks_EnsureImage_Call struct {
	*mock.Call
}

// EnsureImage is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
func (_e *MockTasks_Expecter) EnsureImage(ctx any, ref any) *MockTasks_EnsureImage_Call {
	return &MockTasks_EnsureImage_Call{Call: _e.mock.On("EnsureImage", ctx, ref)}
}

func (_c *MockTasks_EnsureImage_Call) Run(run func(ctx context.Context, ref string)) *MockTasks_EnsureImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTasks_EnsureImage_Call) Return(err error) *MockTasks_EnsureImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTasks_EnsureImage_Call) RunAndReturn(run func(ctx context.Context, ref string) error) *MockTasks_EnsureImage_Call {
	_c.Call.Return(run)
	return _c
}

// NetworkContainers provides a mock function for the type MockTasks
func (_mock *MockTasks) NetworkContainers(ctx context.Context, networkID string) ([]string, error) {
	ret := _mock.Called(ctx, networkID)

	if len(ret) == 0 {
		panic("no return value specified for NetworkContainers")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, networkID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, networkID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, networkID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTasks_NetworkContainers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NetworkContainers'
type MockTasks_NetworkContainers_Call struct {
	*mock.Call
}

// NetworkContainers is a helper method to define mock.On call
//   - ctx context.Context
//   - networkID string
func (_e *MockTasks_Expecter) NetworkContainers(ctx any, networkID any) *MockTasks_NetworkContainers_Call {
	return &MockTasks_NetworkContainers_Call{Call: _e.mock.On("NetworkContainers", ctx, networkID)}
}

func (_c *MockTasks_NetworkContainers_Call) Run(run func(ctx context.Context, networkID string)) *MockTasks_NetworkContainers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTasks_NetworkContainers_Call) Return(strings []string, err error) *MockTasks_NetworkContainers_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockTasks_NetworkContainers_Call) RunAndReturn(run func(ctx context.Context, networkID string) ([]string, error)) *MockTasks_NetworkContainers_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveContainer provides a mock function for the type MockTasks
func (_mock *MockTasks) RemoveContainer(ctx context.Context, containerID string) error {
	ret := _mock.Called(ctx, containerID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, containerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTasks_RemoveContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveContainer'
type MockTasks_RemoveContainer_Call struct {
	*mock.Call
}

// RemoveContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
func (_e *MockTasks_Expecter) RemoveContainer(ctx any, containerID any) *MockTasks_RemoveContainer_Call {
	return &MockTasks_RemoveContainer_Call{Call: _e.mock.On("RemoveContainer", ctx, containerID)}
}

func (_c *MockTasks_RemoveContainer_Call) Run(run func(ctx context.Context, containerID string)) *MockTasks_RemoveContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTasks_RemoveContainer_Call) Return(err error) *MockTasks_RemoveContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTasks_RemoveContainer_Call) RunAndReturn(run func(ctx context.Context, containerID string) error) *MockTasks_RemoveContainer_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveNetwork provides a mock function for the type MockTasks
func (_mock *MockTasks) RemoveNetwork(ctx context.Context, networkID string) error {
	ret := _mock.Called(ctx, networkID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveNetwork")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, networkID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTasks_RemoveNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveNetwork'
type MockTasks_RemoveNetwork_Call struct {
	*mock.Call
}

// RemoveNetwork is a helper method to define mock.On call
//   - ctx context.Context
//   - networkID string
func (_e *MockTasks_Expecter) RemoveNetwork(ctx any, networkID any) *MockTasks_RemoveNetwork_Call {
	return &MockTasks_RemoveNetwork_Call{Call: _e.mock.On("RemoveNetwork", ctx, networkID)}
}

func (_c *MockTasks_RemoveNetwork_Call) Run(run func(ctx context.Context, networkID string)) *MockTasks_RemoveNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTasks_RemoveNetwork_Call) Return(err error) *MockTasks_RemoveNetwork_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTasks_RemoveNetwork_Call) RunAndReturn(run func(ctx context.Context, networkID string) error) *MockTasks_RemoveNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// StartContainer provides a mock function for the type MockTasks
func (_mock *MockTasks) StartContainer(ctx context.Context, containerID string) error {
	ret := _mock.Called(ctx, containerID)

	if len(ret) == 0 {
		panic("no return value specified for StartContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, containerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTasks_StartContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartContainer'
type MockTasks_StartContainer_Call struct {
	*mock.Call
}

// StartContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
func (_e *MockTasks_Expecter) StartContainer(ctx any, containerID any) *MockTasks_StartContainer_Call {
	return &MockTasks_StartContainer_Call{Call: _e.mock.On("StartContainer", ctx, containerID)}
}

func (_c *MockTasks_StartContainer_Call) Run(run func(ctx context.Context, containerID string)) *MockTasks_StartContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTasks_StartContainer_Call) Return(err error) *MockTasks_StartContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTasks_StartContainer_Call) RunAndReturn(run func(ctx context.Context, containerID string) error) *MockTasks_StartContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StopContainer provides a mock function for the type MockTasks
func (_mock *MockTasks) StopContainer(ctx context.Context, containerID string) error {
	ret := _mock.Called(ctx, containerID)

	if len(ret) == 0 {
		panic("no return value specified for StopContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, containerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTasks_StopContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopContainer'
type MockTasks_StopContainer_Call struct {
	*mock.Call
}

// StopContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
func (_e *MockTasks_Expecter) StopContainer(ctx any, containerID any) *MockTasks_StopContainer_Call {
	return &MockTasks_StopContainer_Call{Call: _e.mock.On("StopContainer", ctx, containerID)}
}

func (_c *MockTasks_StopContainer_Call) Run(run func(ctx context.Context, containerID string)) *MockTasks_StopContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTasks_StopContainer_Call) Return(err error) *MockTasks_StopContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTasks_StopContainer_Call) RunAndReturn(run func(ctx context.Context, containerID string) error) *MockTasks_StopContainer_Call {
	_c.Call.Return(run)
	return _c
}
